apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kookaburra
  labels: {app: kookaburra}
spec:
  replicas: 3
  template:
    metadata: {labels: {app: kookaburra}}
    spec:
      containers:
      - name: kookaburra
        image: lusotycoon/kookaburra:${TAG}
        command:
        ports:
          - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: kookaburra
spec:
  type: LoadBalancer
  selector:
    app: kookaburra
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
